//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_dNArv_ProyectoE_InteractUI;
        
        private static SteamVR_Action_Boolean p_dNArv_ProyectoE_Teleport;
        
        private static SteamVR_Action_Boolean p_dNArv_ProyectoE_GrabPinch;
        
        private static SteamVR_Action_Boolean p_dNArv_ProyectoE_GrabGrip;
        
        private static SteamVR_Action_Pose p_dNArv_ProyectoE_Pose;
        
        private static SteamVR_Action_Skeleton p_dNArv_ProyectoE_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_dNArv_ProyectoE_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_dNArv_ProyectoE_Squeeze;
        
        private static SteamVR_Action_Boolean p_dNArv_ProyectoE_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_dNArv_ProyectoE_SnapTurnLeft;
        
        private static SteamVR_Action_Boolean p_dNArv_ProyectoE_SnapTurnRight;
        
        private static SteamVR_Action_Boolean p_dNArv_ProyectoE_Press;
        
        private static SteamVR_Action_Vector2 p_dNArv_ProyectoE_TouchPadPosition;
        
        private static SteamVR_Action_Vibration p_dNArv_ProyectoE_Haptic;
        
        private static SteamVR_Action_Vector2 p_platformer_Move;
        
        private static SteamVR_Action_Boolean p_platformer_Jump;
        
        private static SteamVR_Action_Vector2 p_buggy_Steering;
        
        private static SteamVR_Action_Single p_buggy_Throttle;
        
        private static SteamVR_Action_Boolean p_buggy_Brake;
        
        private static SteamVR_Action_Boolean p_buggy_Reset;
        
        private static SteamVR_Action_Pose p_mixedreality_ExternalCamera;
        
        public static SteamVR_Action_Boolean dNArv_ProyectoE_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean dNArv_ProyectoE_Teleport
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean dNArv_ProyectoE_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean dNArv_ProyectoE_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose dNArv_ProyectoE_Pose
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton dNArv_ProyectoE_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton dNArv_ProyectoE_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single dNArv_ProyectoE_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean dNArv_ProyectoE_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean dNArv_ProyectoE_SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_SnapTurnLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean dNArv_ProyectoE_SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_SnapTurnRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean dNArv_ProyectoE_Press
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_Press.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 dNArv_ProyectoE_TouchPadPosition
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_TouchPadPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vibration dNArv_ProyectoE_Haptic
        {
            get
            {
                return SteamVR_Actions.p_dNArv_ProyectoE_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 platformer_Move
        {
            get
            {
                return SteamVR_Actions.p_platformer_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean platformer_Jump
        {
            get
            {
                return SteamVR_Actions.p_platformer_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 buggy_Steering
        {
            get
            {
                return SteamVR_Actions.p_buggy_Steering.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single buggy_Throttle
        {
            get
            {
                return SteamVR_Actions.p_buggy_Throttle.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Brake
        {
            get
            {
                return SteamVR_Actions.p_buggy_Brake.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Reset
        {
            get
            {
                return SteamVR_Actions.p_buggy_Reset.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose mixedreality_ExternalCamera
        {
            get
            {
                return SteamVR_Actions.p_mixedreality_ExternalCamera.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.dNArv_ProyectoE_InteractUI,
                    SteamVR_Actions.dNArv_ProyectoE_Teleport,
                    SteamVR_Actions.dNArv_ProyectoE_GrabPinch,
                    SteamVR_Actions.dNArv_ProyectoE_GrabGrip,
                    SteamVR_Actions.dNArv_ProyectoE_Pose,
                    SteamVR_Actions.dNArv_ProyectoE_SkeletonLeftHand,
                    SteamVR_Actions.dNArv_ProyectoE_SkeletonRightHand,
                    SteamVR_Actions.dNArv_ProyectoE_Squeeze,
                    SteamVR_Actions.dNArv_ProyectoE_HeadsetOnHead,
                    SteamVR_Actions.dNArv_ProyectoE_SnapTurnLeft,
                    SteamVR_Actions.dNArv_ProyectoE_SnapTurnRight,
                    SteamVR_Actions.dNArv_ProyectoE_Press,
                    SteamVR_Actions.dNArv_ProyectoE_TouchPadPosition,
                    SteamVR_Actions.dNArv_ProyectoE_Haptic,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.dNArv_ProyectoE_InteractUI,
                    SteamVR_Actions.dNArv_ProyectoE_Teleport,
                    SteamVR_Actions.dNArv_ProyectoE_GrabPinch,
                    SteamVR_Actions.dNArv_ProyectoE_GrabGrip,
                    SteamVR_Actions.dNArv_ProyectoE_Pose,
                    SteamVR_Actions.dNArv_ProyectoE_SkeletonLeftHand,
                    SteamVR_Actions.dNArv_ProyectoE_SkeletonRightHand,
                    SteamVR_Actions.dNArv_ProyectoE_Squeeze,
                    SteamVR_Actions.dNArv_ProyectoE_HeadsetOnHead,
                    SteamVR_Actions.dNArv_ProyectoE_SnapTurnLeft,
                    SteamVR_Actions.dNArv_ProyectoE_SnapTurnRight,
                    SteamVR_Actions.dNArv_ProyectoE_Press,
                    SteamVR_Actions.dNArv_ProyectoE_TouchPadPosition,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.dNArv_ProyectoE_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.dNArv_ProyectoE_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.dNArv_ProyectoE_Pose,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.dNArv_ProyectoE_InteractUI,
                    SteamVR_Actions.dNArv_ProyectoE_Teleport,
                    SteamVR_Actions.dNArv_ProyectoE_GrabPinch,
                    SteamVR_Actions.dNArv_ProyectoE_GrabGrip,
                    SteamVR_Actions.dNArv_ProyectoE_HeadsetOnHead,
                    SteamVR_Actions.dNArv_ProyectoE_SnapTurnLeft,
                    SteamVR_Actions.dNArv_ProyectoE_SnapTurnRight,
                    SteamVR_Actions.dNArv_ProyectoE_Press,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.dNArv_ProyectoE_Squeeze,
                    SteamVR_Actions.buggy_Throttle};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.dNArv_ProyectoE_TouchPadPosition,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.buggy_Steering};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.dNArv_ProyectoE_SkeletonLeftHand,
                    SteamVR_Actions.dNArv_ProyectoE_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.dNArv_ProyectoE_InteractUI,
                    SteamVR_Actions.dNArv_ProyectoE_Teleport,
                    SteamVR_Actions.dNArv_ProyectoE_GrabPinch,
                    SteamVR_Actions.dNArv_ProyectoE_GrabGrip,
                    SteamVR_Actions.dNArv_ProyectoE_Squeeze,
                    SteamVR_Actions.dNArv_ProyectoE_HeadsetOnHead,
                    SteamVR_Actions.dNArv_ProyectoE_SnapTurnLeft,
                    SteamVR_Actions.dNArv_ProyectoE_SnapTurnRight,
                    SteamVR_Actions.dNArv_ProyectoE_Press,
                    SteamVR_Actions.dNArv_ProyectoE_TouchPadPosition,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_dNArv_ProyectoE_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DNArv_ProyectoE/in/InteractUI")));
            SteamVR_Actions.p_dNArv_ProyectoE_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DNArv_ProyectoE/in/Teleport")));
            SteamVR_Actions.p_dNArv_ProyectoE_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DNArv_ProyectoE/in/GrabPinch")));
            SteamVR_Actions.p_dNArv_ProyectoE_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DNArv_ProyectoE/in/GrabGrip")));
            SteamVR_Actions.p_dNArv_ProyectoE_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/DNArv_ProyectoE/in/Pose")));
            SteamVR_Actions.p_dNArv_ProyectoE_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/DNArv_ProyectoE/in/SkeletonLeftHand")));
            SteamVR_Actions.p_dNArv_ProyectoE_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/DNArv_ProyectoE/in/SkeletonRightHand")));
            SteamVR_Actions.p_dNArv_ProyectoE_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/DNArv_ProyectoE/in/Squeeze")));
            SteamVR_Actions.p_dNArv_ProyectoE_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DNArv_ProyectoE/in/HeadsetOnHead")));
            SteamVR_Actions.p_dNArv_ProyectoE_SnapTurnLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DNArv_ProyectoE/in/SnapTurnLeft")));
            SteamVR_Actions.p_dNArv_ProyectoE_SnapTurnRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DNArv_ProyectoE/in/SnapTurnRight")));
            SteamVR_Actions.p_dNArv_ProyectoE_Press = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/DNArv_ProyectoE/in/Press")));
            SteamVR_Actions.p_dNArv_ProyectoE_TouchPadPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/DNArv_ProyectoE/in/TouchPadPosition")));
            SteamVR_Actions.p_dNArv_ProyectoE_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/DNArv_ProyectoE/out/Haptic")));
            SteamVR_Actions.p_platformer_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/platformer/in/Move")));
            SteamVR_Actions.p_platformer_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/platformer/in/Jump")));
            SteamVR_Actions.p_buggy_Steering = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/buggy/in/Steering")));
            SteamVR_Actions.p_buggy_Throttle = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/buggy/in/Throttle")));
            SteamVR_Actions.p_buggy_Brake = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Brake")));
            SteamVR_Actions.p_buggy_Reset = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Reset")));
            SteamVR_Actions.p_mixedreality_ExternalCamera = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/mixedreality/in/ExternalCamera")));
        }
    }
}
